### ISSUE TITLE
Converting image to byte array

### ISSUE THREAD

**Issue by DefiNode** [hacksics/lilygo-t5-47-ha#1]
Hi,

great app! Thanks for sharing.
How did you exactly convert the images to the byte arrays? 
Thanks!

**Comment by hacksics** [comment]
Hi @DefiNode  

You can use the fontconverter script in https://github.com/vroland/epdiy. 

Refer to https://github.com/vroland/epdiy/issues/87 if you encounter any issues. 

Thanks

**Comment by DefiNode** [comment]
Thanks I'll try

**Comment by DefiNode** [comment]
Script does't execute on my W10 mashine :(

Any chance you can convert the attached image in 100x100?

I can place your byte arays no problem, but can't get my image to work. :(

![100](https://user-images.githubusercontent.com/84664789/130814402-715058ed-1436-4c8b-abf2-5d77ea7f7a1c.jpg)

**Comment by DefiNode** [comment]
Got it! 
Had to "pip install Pillow" first!
It works!
Thank you!
